# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bA5_uem61mEqy_P9X-l6si0tH4ZyhOFg

## Load and Combine Datasets

### Subtask:
Load the provided datasets, '/content/Dataset/multilingual_dataset_test_final.csv' and '/content/Dataset/multilingual_dataset_train_final.csv', into pandas DataFrames and combine them into a single DataFrame for further processing.
"""

import pandas as pd
import csv

# Set a larger field size limit to handle potentially very long text fields
csv.field_size_limit(10000000) # Setting a limit of 10MB, adjust as needed

# Load the test dataset
df_test = pd.read_csv('/content/Dataset/multilingual_dataset_test_final.csv', engine='python', on_bad_lines='skip')
print("df_test loaded successfully.")

# Load the train dataset
df_train = pd.read_csv('/content/Dataset/multilingual_dataset_train_final.csv', engine='python', on_bad_lines='skip')
print("df_train loaded successfully.")

# Combine the two DataFrames
df_combined = pd.concat([df_test, df_train], ignore_index=True)
print("DataFrames combined successfully.")

# Display the head of the combined DataFrame
print("Head of the combined DataFrame (df_combined):")
df_combined.head()

"""## Data Preprocessing
Perform necessary preprocessing steps on the combined text data, such as handling missing values, converting text to lowercase, and any other relevant cleaning to prepare it for NLP feature extraction.

"""

print("Missing values before preprocessing:")
print(df_combined.isnull().sum())

print(df_combined.columns)

df_combined['text'] = df_combined['text'].str.lower()
print("Text column converted to lowercase.")

print("Head of the DataFrame after converting text to lowercase:")
df_combined.head()

"""## Feature Extraction using NLP Embeddings
Generate numerical feature vectors (embeddings) from the preprocessed text data using a Sentence Transformer model.

"""

!pip install -U sentence-transformers
print("sentence-transformers library installed successfully.")

from sentence_transformers import SentenceTransformer
import torch

# Check if GPU is available and use it, otherwise use CPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# Load a pre-trained multilingual Sentence Transformer model
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2', device=device)
print("Sentence Transformer model 'paraphrase-multilingual-MiniLM-L12-v2' loaded successfully.")

# Generate embeddings for the 'text' column
# Convert text column to a list for encoding
texts = df_combined['text'].tolist()
text_embeddings = model.encode(texts, show_progress_bar=True)
print("Embeddings generated successfully.")

# Store embeddings in a new column (optional, but good for verification)
df_combined['embeddings'] = list(text_embeddings)

# Print the shape of the text_embeddings
print("Shape of text_embeddings:", text_embeddings.shape)

"""**Reasoning**:
With the text embeddings generated, the next step is to prepare the data for model training by splitting it into training and testing sets. I will use scikit-learn's `train_test_split` function for this purpose, applying a 75:25 ratio as specified in the main task, and ensuring the split is stratified to maintain the class distribution of the labels.


"""

from sklearn.model_selection import train_test_split

# Define features (X) and labels (y)
X = text_embeddings
y = df_combined['labels'].values

# Split the data into training and testing sets (75:25 ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""**Reasoning**:
Following the data splitting for training and testing, I will now further split the training set (`X_train`, `y_train`) to create a separate validation set, adhering to a common practice of an 80:20 split to prepare the data for model training and evaluation, ensuring the 'validation sets' requirement from the main task is met.


"""

from sklearn.model_selection import train_test_split

# Split the training data into training and validation sets (e.g., 80:20 ratio)
X_train_final, X_val, y_train_final, y_val = train_test_split(X_train, y_train, test_size=0.20, random_state=42, stratify=y_train)

print(f"Shape of X_train_final: {X_train_final.shape}")
print(f"Shape of X_val: {X_val.shape}")
print(f"Shape of y_train_final: {y_train_final.shape}")
print(f"Shape of y_val: {y_val.shape}")

"""LogisticRegression



"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Instantiate a Logistic Regression model
# Set max_iter to a higher value to ensure convergence and random_state for reproducibility
log_reg_model = LogisticRegression(max_iter=1000, random_state=42)
print("Logistic Regression model instantiated.")

# Train the model on the final training data
log_reg_model.fit(X_train_final, y_train_final)
print("Logistic Regression model trained successfully.")

# Make predictions on the validation set
y_pred_val = log_reg_model.predict(X_val)
print("Predictions made on the validation set.")

# Evaluate the model on the validation set
print("\n--- Validation Set Evaluation ---")
print("Classification Report:")
print(classification_report(y_val, y_pred_val))

accuracy = accuracy_score(y_val, y_pred_val)
precision = precision_score(y_val, y_pred_val, average='weighted')
recall = recall_score(y_val, y_pred_val, average='weighted')
f1 = f1_score(y_val, y_pred_val, average='weighted')

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

# Display the confusion matrix
print("\nConfusion Matrix:")
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(y_val, y_pred_val, ax=ax, cmap='Blues')
plt.title('Logistic Regression Confusion Matrix')
plt.show()

from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

# Make predictions on the test set
y_pred_test = log_reg_model.predict(X_test)
print("Predictions made on the test set.")

# Evaluate the model on the test set
print("\n--- Test Set Evaluation ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_test))

accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test, average='weighted')
recall_test = recall_score(y_test, y_pred_test, average='weighted')
f1_test = f1_score(y_test, y_pred_test, average='weighted')

print(f"Accuracy (Test Set): {accuracy_test:.4f}")
print(f"Precision (Test Set): {precision_test:.4f}")
print(f"Recall (Test Set): {recall_test:.4f}")
print(f"F1-score (Test Set): {f1_test:.4f}")

"""*   **Feature Extraction:** Text features were extracted using the `paraphrase-multilingual-MiniLM-L12-v2` Sentence Transformer model, generating 384-dimensional embeddings for each text entry. A total of 89,157 text entries were processed.
*   **Data Splitting:** The dataset was split into training, validation, and testing sets using a stratified approach:
    *   Training set: 53,493 samples for model training.
    *   Validation set: 13,374 samples for hyperparameter tuning and preliminary evaluation.
    *   Test set: 22,290 samples for final, unbiased model evaluation.

## Train and Evaluate Support Vector Machine (SVM)
"""

from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    classification_report,
    ConfusionMatrixDisplay,
    accuracy_score,
    f1_score,
    precision_score,
    recall_score
)
import matplotlib.pyplot as plt
import numpy as np

# ----------------------------------
# 1️⃣ Create Pipeline (Scaling + SVM)
# ----------------------------------
svm_model = Pipeline([
    ("scaler", StandardScaler()),  # Important for SVM
    ("svm", LinearSVC(
        C=1.0,
        max_iter=5000,
        class_weight='balanced',   # Good for imbalanced data
        random_state=42
    ))
])

# ----------------------------------
# 2️⃣ Train Model
# ----------------------------------
svm_model.fit(X_train_final, y_train_final)

# ----------------------------------
# 3️⃣ Predictions
# ----------------------------------
y_pred_svm = svm_model.predict(X_test)

# ----------------------------------
# 4️⃣ Evaluation Metrics
# ----------------------------------
acc = accuracy_score(y_test, y_pred_svm)
f1 = f1_score(y_test, y_pred_svm, average='weighted')
prec = precision_score(y_test, y_pred_svm, average='weighted')
rec = recall_score(y_test, y_pred_svm, average='weighted')

print("\n--- Support Vector Machine Test Set Evaluation ---")
print(classification_report(y_test, y_pred_svm))

print(f"Accuracy  : {acc:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")

# ----------------------------------
# 5️⃣ Confusion Matrix
# ----------------------------------
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_svm,
    ax=ax,
    cmap='Blues'
)

plt.title('SVM Confusion Matrix')
plt.show()

"""## Train and Evaluate XGBoost Classifier


"""

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Instantiate an XGBoost classifier
# Set random_state for reproducibility
xgb_model = XGBClassifier(random_state=42, eval_metric='logloss')
print("XGBoost model instantiated.")

# Train the XGBoost model on the final training data
xgb_model.fit(X_train_final, y_train_final)
print("XGBoost model trained successfully.")

# Make predictions on the test set
y_pred_xgb = xgb_model.predict(X_test)
print("Predictions made on the test set.")

# Print the classification report
print("\n--- XGBoost Test Set Evaluation ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_xgb))

# Display the confusion matrix
print("\nConfusion Matrix:")
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_xgb, ax=ax, cmap='Blues')
plt.title('XGBoost Confusion Matrix')
plt.show()

"""## Train and Evaluate LightGBM Classifier


"""

from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Instantiate an LGBMClassifier model
lgbm_model = LGBMClassifier(random_state=42)
print("LightGBM model instantiated.")

# Train the LightGBM model on the final training data
lgbm_model.fit(X_train_final, y_train_final)
print("LightGBM model trained successfully.")

# Make predictions on the test set
y_pred_lgbm = lgbm_model.predict(X_test)
print("Predictions made on the test set.")

# Print the classification report
print("\n--- LightGBM Test Set Evaluation ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_lgbm))

# Display the confusion matrix
print("\nConfusion Matrix:")
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lgbm, ax=ax, cmap='Blues')
plt.title('LightGBM Confusion Matrix')
plt.show()

"""## Train and Evaluate CatBoost Classifier

### Subtask:
Train a CatBoost classifier on the training data (`X_train_final`, `y_train_final`). Evaluate its performance on the test set (`X_test`, `y_test`), print the classification report, and display its confusion matrix.

"""

!pip install catboost
print("CatBoost library installation initiated.")

from catboost import CatBoostClassifier
from sklearn.metrics import (
    classification_report,
    ConfusionMatrixDisplay,
    accuracy_score,
    f1_score,
    precision_score,
    recall_score
)
import matplotlib.pyplot as plt
import numpy as np

# ----------------------------------
# 1️⃣ Instantiate Optimized CatBoost
# ----------------------------------
catboost_model = CatBoostClassifier(
    iterations=500,          # number of trees
    learning_rate=0.05,      # smaller = better learning
    depth=6,                 # tree depth
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0
)

# ----------------------------------
# 2️⃣ Train Model with Early Stopping
# ----------------------------------
catboost_model.fit(
    X_train_final,
    y_train_final,
    eval_set=(X_test, y_test),
    early_stopping_rounds=50,
    use_best_model=True
)

# ----------------------------------
# 3️⃣ Predictions
# ----------------------------------
y_pred_catboost = catboost_model.predict(X_test)

# ----------------------------------
# 4️⃣ Evaluation Metrics
# ----------------------------------
acc = accuracy_score(y_test, y_pred_catboost)
f1 = f1_score(y_test, y_pred_catboost, average='weighted')
prec = precision_score(y_test, y_pred_catboost, average='weighted')
rec = recall_score(y_test, y_pred_catboost, average='weighted')

print("\n--- CatBoost Test Set Evaluation ---")
print(classification_report(y_test, y_pred_catboost))

print(f"Accuracy  : {acc:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")

# ----------------------------------
# 5️⃣ Confusion Matrix
# ----------------------------------
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_catboost,
    ax=ax,
    cmap='Blues'
)
plt.title('CatBoost Confusion Matrix')
plt.show()

"""## Train and Evaluate Feed-Forward Neural Network

Build and train a simple Feed-Forward Neural Network (Multi-Layer Perceptron) using the text_embeddings as input features for classification. Evaluate its performance on the test set (X_test, y_test),

"""

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Instantiate an MLPClassifier model
# Using a single hidden layer with 100 neurons, increased max_iter for convergence,
# and random_state for reproducibility.
mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=200, random_state=42, verbose=True)
print("MLPClassifier model instantiated.")

# Train the MLPClassifier model on the final training data
mlp_model.fit(X_train_final, y_train_final)
print("MLPClassifier model trained successfully.")

# Make predictions on the test set
y_pred_mlp = mlp_model.predict(X_test)
print("Predictions made on the test set.")

# Print the classification report
print("\n--- Feed-Forward Neural Network Test Set Evaluation ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_mlp))

# Display the confusion matrix
print("\nConfusion Matrix:")
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_mlp, ax=ax, cmap='Blues')
plt.title('Feed-Forward Neural Network Confusion Matrix')
plt.show()

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Assuming y_test, y_pred_test, y_pred_gnb, y_pred_svm, y_pred_xgb, y_pred_lgbm, y_pred_catboost, y_pred_mlp are available from previous steps

results = []

def evaluate_model(model_name, y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    results.append({
        'Model': model_name,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1
    })

# Evaluate Logistic Regression (results already available as accuracy_test, precision_test, recall_test, f1_test)
results.append({
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_test,
    'Precision': precision_test,
    'Recall': recall_test,
    'F1-Score': f1_test
})

# Evaluate other models
# Removed Gaussian Naive Bayes from the evaluation as per instructions
# evaluate_model('Gaussian Naive Bayes', y_test, y_pred_gnb) # This line was removed
evaluate_model('Support Vector Machine', y_test, y_pred_svm)
evaluate_model('XGBoost', y_test, y_pred_xgb)
evaluate_model('LightGBM', y_test, y_pred_lgbm)
evaluate_model('CatBoost', y_test, y_pred_catboost)
evaluate_model('Feed-Forward Neural Network', y_test, y_pred_mlp)

df_results = pd.DataFrame(results)
print("Model Evaluation Results:")
print(df_results.round(4))

import matplotlib.pyplot as plt
import seaborn as sns

# Plotting the comparison
df_results_melted = df_results.melt(id_vars='Model', var_name='Metric', value_name='Score')

plt.figure(figsize=(14, 8))
sns.barplot(x='Model', y='Score', hue='Metric', data=df_results_melted, palette='viridis')
plt.title('Comparison of Model Performance on Test Set')
plt.ylabel('Score')
plt.xlabel('Model')
plt.ylim(0, 1) # Metrics are typically between 0 and 1
plt.xticks(rotation=45, ha='right')
plt.legend(title='Metric')
plt.tight_layout()
plt.show()

"""## Check and Handle Data Imbalance

Analyze the class distribution of the labels in `y_train_final`, `y_val`, and `y_test` to detect any significant data imbalance.

"""

import pandas as pd

print("Class distribution for y_train_final:")
y_train_final_series = pd.Series(y_train_final)
class_counts_train = y_train_final_series.value_counts()
class_percentages_train = y_train_final_series.value_counts(normalize=True) * 100

print("Counts:\n", class_counts_train)
print("Percentages:\n", class_percentages_train.round(2))

print("\nClass distribution for y_val:")
y_val_series = pd.Series(y_val)
class_counts_val = y_val_series.value_counts()
class_percentages_val = y_val_series.value_counts(normalize=True) * 100

print("Counts:\n", class_counts_val)
print("Percentages:\n", class_percentages_val.round(2))

print("\nClass distribution for y_test:")
y_test_series = pd.Series(y_test)
class_counts_test = y_test_series.value_counts()
class_percentages_test = y_test_series.value_counts(normalize=True) * 100

print("Counts:\n", class_counts_test)
print("Percentages:\n", class_percentages_test.round(2))

"""## Build and Train LSTM Model
Build a simple Long Short-Term Memory (LSTM) recurrent neural network model, using the `text_embeddings` as input features. Train the model on the training data (`X_train_final`, `y_train_final`), evaluate its performance on the test set (`X_test`, `y_test`)Incorporate techniques to prevent overfitting, such as dropout.

"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Reshape, LSTM, Dense, Dropout
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

# Ensure TensorFlow uses GPU if available
device = 'cuda' if tf.config.list_physical_devices('GPU') else 'cpu'
print(f"Using TensorFlow device: {device}")

# Determine the input dimension for the LSTM model
input_dim = X_train_final.shape[1] # Dimensionality of text_embeddings
print(f"Input dimension for LSTM: {input_dim}")

# Build a Keras Sequential model
lstm_model = Sequential([
    Input(shape=(input_dim,)), # Input layer to define the input shape
    Reshape((1, input_dim)), # Reshape layer for LSTM input (timesteps, features)
    LSTM(128),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid') # Output layer for binary classification
])
print("LSTM model constructed.")

# Compile the model
lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print("LSTM model compiled.")

# Display model summary
lstm_model.summary()

# Train the LSTM model
# Convert labels to float32 for binary_crossentropy if they are not already
y_train_final_float = y_train_final.astype(np.float32)
y_val_float = y_val.astype(np.float32)

history = lstm_model.fit(
    X_train_final,
    y_train_final_float,
    epochs=10, # Set an appropriate number of epochs
    batch_size=32, # Set an appropriate batch size
    validation_data=(X_val, y_val_float),
    verbose=1
)
print("LSTM model trained successfully.")

# Make predictions on the X_test data
y_pred_lstm_proba = lstm_model.predict(X_test)
y_pred_lstm = (y_pred_lstm_proba > 0.5).astype(int)
print("Predictions made on the test set.")

# Print the classification report
print("\n--- LSTM Test Set Evaluation ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_lstm))

# Display the confusion matrix
print("\nConfusion Matrix:")
fig, ax = plt.subplots(figsize=(6, 6))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lstm, ax=ax, cmap='Blues')
plt.title('LSTM Confusion Matrix')
plt.show()

"""Transformers"""

pip install transformers sentence-transformers torch

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, f1_score, accuracy_score

print("Initializing models and preparing data...")

# --- STEP 1: INITIALIZE MODELS ---
# Sentence Transformers
labse_model = SentenceTransformer('sentence-transformers/LaBSE')
paraphrase_model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')
distiluse_model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v2')

# AutoModels (Standard Transformers)
xlmr_tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
xlmr_model = AutoModel.from_pretrained("xlm-roberta-base")

mbert_tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
mbert_model = AutoModel.from_pretrained("bert-base-multilingual-cased")

models_to_run = {
    "LaBSE": labse_model,
    "Paraphrase_Multilingual": paraphrase_model,
    "DistilUSE": distiluse_model,
    "XLM_RoBERTa": (xlmr_tokenizer, xlmr_model),
    "mBERT": (mbert_tokenizer, mbert_model)
}

# --- STEP 2: PREPARE DATA ---
df_combined = df_combined.reset_index(drop=True)
sentences = df_combined['text'].fillna("").astype(str).tolist()
y = df_combined['labels']

# Initialize comparison results list
comparison_results = []
print("Models initialized and data prepared.")

"""### Evaluating LaBSE Embeddings with LinearSVC"""

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, ConfusionMatrixDisplay,
    f1_score, accuracy_score, precision_score, recall_score
)

# -------------------------
# SETTINGS
# -------------------------
model_name = "LaBSE"
embedding_cache_file = f"{model_name}_embeddings.npy"
batch_size = 128  # Larger batch size for speed
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")
print(f"\n--- Processing & Evaluating: {model_name} ---")

# -------------------------
# LOAD MODEL
# -------------------------
model_obj = models_to_run[model_name]

# -------------------------
# FEATURE EXTRACTION WITH CACHE + GPU
# -------------------------
if os.path.exists(embedding_cache_file):
    print("Loading cached embeddings...")
    X_embeddings = np.load(embedding_cache_file)
else:
    print("Extracting embeddings...")

    if hasattr(model_obj, 'encode'):  # SentenceTransformer
        X_embeddings = model_obj.encode(
            sentences,
            batch_size=batch_size,
            show_progress_bar=True,
            device=device
        )
    else:
        tokenizer, transformer_model = model_obj
        transformer_model.to(device)
        transformer_model.eval()
        embeddings_list = []

        for i in tqdm(range(0, len(sentences), batch_size)):
            batch = sentences[i:i+batch_size]
            inputs = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=128,
                return_tensors="pt"
            ).to(device)

            with torch.no_grad():
                output = transformer_model(**inputs)
                batch_embeddings = output.last_hidden_state[:, 0, :].cpu().numpy()
                embeddings_list.append(batch_embeddings)

        X_embeddings = np.vstack(embeddings_list)

    np.save(embedding_cache_file, X_embeddings)
    print("Saved embeddings to cache.")

# -------------------------
# TRAIN / TEST SPLIT
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# TRAIN LinearSVC
# -------------------------
svm_model = LinearSVC(max_iter=5000, random_state=42, dual=False)
svm_model.fit(X_train, y_train)

# -------------------------
# PREDICTIONS & METRICS
# -------------------------
y_pred = svm_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
prec = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')

# Store results for final comparison
comparison_results.append({
    "Model": model_name,
    "Accuracy": acc,
    "F1-Score": f1,
    "Precision": prec,
    "Recall": rec
})

# Print metrics
print(classification_report(y_test, y_pred))
print(f"Accuracy: {acc:.4f}, F1-Score: {f1:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}")

# -------------------------
# CONFUSION MATRIX
# -------------------------
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax, cmap='Blues')
plt.title(f'Confusion Matrix: {model_name}')
plt.show()

"""### Evaluating Paraphrase Multilingual Embeddings with LinearSVC"""

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, ConfusionMatrixDisplay,
    accuracy_score, f1_score, precision_score, recall_score
)

# -------------------------
# SETTINGS
# -------------------------
model_name = "Paraphrase_Multilingual"
embedding_cache_file = f"{model_name}_embeddings.npy"
batch_size = 128  # Larger batch size for speed
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")
print(f"\n--- Processing & Evaluating: {model_name} ---")

# -------------------------
# LOAD MODEL
# -------------------------
model_obj = models_to_run[model_name]

# -------------------------
# FEATURE EXTRACTION WITH CACHE
# -------------------------
if os.path.exists(embedding_cache_file):
    print("Loading cached embeddings...")
    X_embeddings = np.load(embedding_cache_file)
else:
    print("Extracting embeddings...")

    if hasattr(model_obj, 'encode'):  # SentenceTransformer
        X_embeddings = model_obj.encode(
            sentences,
            batch_size=batch_size,
            show_progress_bar=True,
            device=device
        )
    else:
        tokenizer, transformer_model = model_obj
        transformer_model.to(device)
        transformer_model.eval()
        embeddings_list = []

        for i in tqdm(range(0, len(sentences), batch_size)):
            batch = sentences[i:i+batch_size]
            inputs = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=128,
                return_tensors="pt"
            ).to(device)

            with torch.no_grad():
                output = transformer_model(**inputs)
                batch_embeddings = output.last_hidden_state[:, 0, :].cpu().numpy()
                embeddings_list.append(batch_embeddings)

        X_embeddings = np.vstack(embeddings_list)
    np.save(embedding_cache_file, X_embeddings)
    print("Embeddings saved to cache.")

# -------------------------
# TRAIN / TEST SPLIT
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# TRAIN LinearSVC
# -------------------------
svm_model = LinearSVC(max_iter=5000, random_state=42, dual=False)  # Increased iterations for convergence
svm_model.fit(X_train, y_train)

# -------------------------
# PREDICTIONS & METRICS
# -------------------------
y_pred = svm_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
prec = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')

# Store results
comparison_results.append({
    "Model": model_name,
    "Accuracy": acc,
    "F1-Score": f1,
    "Precision": prec,
    "Recall": rec
})

# Print metrics
print(classification_report(y_test, y_pred))
print(f"Accuracy: {acc:.4f}, F1-Score: {f1:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}")

# -------------------------
# CONFUSION MATRIX
# -------------------------
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax, cmap='Blues')
plt.title(f'Confusion Matrix: {model_name}')
plt.show()

"""### Evaluating DistilUSE Embeddings with LinearSVC"""

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, ConfusionMatrixDisplay,
    accuracy_score, f1_score, precision_score, recall_score
)

# -------------------------
# SETTINGS
# -------------------------
model_name = "DistilUSE"
embedding_cache_file = f"{model_name}_embeddings.npy"
batch_size = 128  # Larger batch size for faster processing
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")
print(f"\n--- Processing & Evaluating: {model_name} ---")

# -------------------------
# LOAD MODEL
# -------------------------
model_obj = models_to_run[model_name]

# -------------------------
# FEATURE EXTRACTION WITH CACHE
# -------------------------
if os.path.exists(embedding_cache_file):
    print("Loading cached embeddings...")
    X_embeddings = np.load(embedding_cache_file)
else:
    print("Extracting embeddings...")

    if hasattr(model_obj, 'encode'):  # SentenceTransformer models
        X_embeddings = model_obj.encode(
            sentences,
            batch_size=batch_size,
            show_progress_bar=True,
            device=device
        )
    else:
        tokenizer, transformer_model = model_obj
        transformer_model.to(device)
        transformer_model.eval()
        embeddings_list = []

        for i in tqdm(range(0, len(sentences), batch_size)):
            batch = sentences[i:i+batch_size]
            inputs = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=128,
                return_tensors="pt"
            ).to(device)

            with torch.no_grad():
                output = transformer_model(**inputs)
                batch_embeddings = output.last_hidden_state[:, 0, :].cpu().numpy()
                embeddings_list.append(batch_embeddings)

        X_embeddings = np.vstack(embeddings_list)

    np.save(embedding_cache_file, X_embeddings)
    print("Embeddings saved to cache.")

# -------------------------
# TRAIN / TEST SPLIT
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# TRAIN LINEAR SVC
# -------------------------
svm_model = LinearSVC(max_iter=5000, random_state=42, dual=False)  # Increased max_iter for convergence
svm_model.fit(X_train, y_train)

# -------------------------
# PREDICTIONS & METRICS
# -------------------------
y_pred = svm_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
prec = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')

# Store results for comparison
comparison_results.append({
    "Model": model_name,
    "Accuracy": acc,
    "F1-Score": f1,
    "Precision": prec,
    "Recall": rec
})

# Print metrics
print(classification_report(y_test, y_pred))
print(f"Accuracy: {acc:.4f}, F1-Score: {f1:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}")

# -------------------------
# CONFUSION MATRIX
# -------------------------
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax, cmap='Blues')
plt.title(f'Confusion Matrix: {model_name}')
plt.show()

"""### Evaluating XLM-RoBERTa Embeddings with LinearSVC"""

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    ConfusionMatrixDisplay,
    f1_score,
    accuracy_score,
    precision_score,
    recall_score,
    roc_curve,
    auc
)
from sklearn.preprocessing import label_binarize

# -------------------------
# SETTINGS
# -------------------------
model_name = "XLM_RoBERTa"
batch_size = 64
embedding_cache_file = f"{model_name}_embeddings.npy"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"\nUsing device: {device}")
print(f"\n--- Processing & Evaluating: {model_name} ---")

# -------------------------
# LOAD MODEL
# -------------------------
model_obj = models_to_run[model_name]

# -------------------------
# FEATURE EXTRACTION
# -------------------------
if os.path.exists(embedding_cache_file):
    print("Loading cached embeddings...")
    X_embeddings = np.load(embedding_cache_file)

else:
    print("Extracting embeddings...")

    if hasattr(model_obj, 'encode'):
        X_embeddings = model_obj.encode(
            sentences,
            batch_size=batch_size,
            show_progress_bar=True,
            device=device
        )
    else:
        tokenizer, transformer_model = model_obj
        transformer_model.to(device)
        transformer_model.eval()

        embeddings_list = []

        for i in tqdm(range(0, len(sentences), batch_size)):
            batch = sentences[i:i+batch_size]

            inputs = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=128,
                return_tensors="pt"
            ).to(device)

            with torch.no_grad():
                output = transformer_model(**inputs)
                batch_embeddings = output.last_hidden_state[:, 0, :]
                embeddings_list.append(batch_embeddings.cpu().numpy())

        X_embeddings = np.vstack(embeddings_list)

    np.save(embedding_cache_file, X_embeddings)
    print("Embeddings saved to cache.")

# -------------------------
# TRAIN / TEST SPLIT
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# -------------------------
# TRAIN LINEAR SVM
# -------------------------
svm_model = SVC(kernel="linear", probability=True, random_state=42)
svm_model.fit(X_train, y_train)

# -------------------------
# PREDICTIONS
# -------------------------
y_pred = svm_model.predict(X_test)
y_prob = svm_model.predict_proba(X_test)

# -------------------------
# METRICS
# -------------------------
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
prec = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print(f"Accuracy  : {acc:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")

# -------------------------
# ADD THIS BLOCK (RESULT STORAGE)
# -------------------------
if 'comparison_results' not in globals():
    comparison_results = []

comparison_results.append({
    "Model": model_name,
    "Accuracy": acc,
    "F1-Score": f1,
    "Precision": prec,
    "Recall": rec
})

# -------------------------
# CONFUSION MATRIX
# -------------------------
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred,
    ax=ax,
    cmap='Blues'
)
plt.title(f'Confusion Matrix: {model_name}')
plt.show()

# -------------------------
# ROC CURVE
# -------------------------
unique_classes = np.unique(y_test)
n_classes = len(unique_classes)

plt.figure(figsize=(7,6))

if n_classes == 2:
    fpr, tpr, _ = roc_curve(y_test, y_prob[:, 1])
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
    plt.plot([0,1],[0,1],'k--')

elif n_classes > 2:
    y_test_bin = label_binarize(y_test, classes=unique_classes)

    for i in range(n_classes):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr,
                 label=f"Class {unique_classes[i]} (AUC = {roc_auc:.2f})")

    plt.plot([0,1],[0,1],'k--')

else:
    print("ROC cannot be computed (only one class present in test set).")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve: {model_name}")
plt.legend()
plt.show()

"""### Evaluating mBERT Embeddings with LinearSVC"""

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, ConfusionMatrixDisplay,
    accuracy_score, f1_score, precision_score, recall_score,
    roc_curve, auc
)
from sklearn.preprocessing import label_binarize

model_name = "mBERT"
embedding_cache_file = f"{model_name}_embeddings.npy"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model_obj = models_to_run[model_name]

# --------- Embedding Extraction ---------
if os.path.exists(embedding_cache_file):
    print("Loading cached embeddings...")
    X_embeddings = np.load(embedding_cache_file)
else:
    print("Extracting embeddings...")
    batch_size = 128

    if hasattr(model_obj, 'encode'):
        X_embeddings = model_obj.encode(
            sentences,
            batch_size=batch_size,
            show_progress_bar=True,
            device=device
        )
    else:
        tokenizer, transformer_model = model_obj
        transformer_model.to(device)
        transformer_model.eval()

        embeddings_list = []
        for i in tqdm(range(0, len(sentences), batch_size)):
            batch = sentences[i:i+batch_size]
            inputs = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=128,
                return_tensors="pt"
            ).to(device)

            with torch.no_grad():
                output = transformer_model(**inputs)
                batch_embeddings = output.last_hidden_state[:, 0, :].cpu().numpy()
                embeddings_list.append(batch_embeddings)

        X_embeddings = np.vstack(embeddings_list)

    np.save(embedding_cache_file, X_embeddings)
    print("Saved embeddings to cache.")

# --------- Train/Test Split ---------
X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings, y, test_size=0.2, random_state=42, stratify=y
)

# --------- Train SVM ---------
svm_model = SGDClassifier(
    loss='hinge',
    max_iter=2000,
    tol=1e-3,
    n_jobs=-1,
    random_state=42
)
svm_model.fit(X_train, y_train)

# --------- Predictions ---------
y_pred = svm_model.predict(X_test)

# For ROC
if hasattr(svm_model, "decision_function"):
    y_scores = svm_model.decision_function(X_test)
else:
    y_scores = y_pred

# --------- Metrics ---------
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
prec = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')

print(classification_report(y_test, y_pred))
print(f"Accuracy: {acc:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")

# --------- ADD THIS BLOCK (RESULT STORAGE) ---------
if 'comparison_results' not in globals():
    comparison_results = []

comparison_results.append({
    "Model": model_name,
    "Accuracy": acc,
    "F1-Score": f1,
    "Precision": prec,
    "Recall": rec
})

# --------- Confusion Matrix ---------
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax, cmap='Blues')
plt.title(f'Confusion Matrix: {model_name}')
plt.show()

# --------- ROC Curve ---------
unique_classes = np.unique(y_test)
n_classes = len(unique_classes)
plt.figure(figsize=(7,6))

if n_classes == 2:
    fpr, tpr, _ = roc_curve(y_test, y_scores)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
    plt.plot([0,1],[0,1],'k--')

elif n_classes > 2:
    y_test_bin = label_binarize(y_test, classes=unique_classes)
    for i in range(n_classes):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_scores[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f"Class {unique_classes[i]} (AUC = {roc_auc:.2f})")

    plt.plot([0,1],[0,1],'k--')

else:
    print("ROC cannot be computed (only one class in test set).")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve: {model_name}")
plt.legend()
plt.show()

"""### Final Model Comparison"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------
# 1️⃣ Convert results list to DataFrame
# ---------------------------------
df = pd.DataFrame(comparison_results)

# ---------------------------------
# 2️⃣ Remove duplicate rows
# ---------------------------------
df = df.drop_duplicates()

# ---------------------------------
# 3️⃣ Aggregate by model (in case model ran multiple times)
# ---------------------------------
df_clean = df.groupby('Model').agg({
    'Accuracy': 'mean',
    'F1-Score': 'mean',
    'Precision': 'mean',
    'Recall': 'mean'
}).reset_index()

# ---------------------------------
# 4️⃣ Sort by F1-Score (Best model on top)
# ---------------------------------
df_clean = df_clean.sort_values(by='F1-Score', ascending=False)

print("\nFinal Model Comparison Table:\n")
print(df_clean)

# ---------------------------------
# 5️⃣ Convert to long format for plotting
# ---------------------------------
df_compare_melted = df_clean.melt(
    id_vars="Model",
    var_name="Metric",
    value_name="Score"
)

# ---------------------------------
# 6️⃣ Plot Comparison Graph
# ---------------------------------
plt.figure(figsize=(14, 7))

sns.barplot(
    x='Model',
    y='Score',
    hue='Metric',
    data=df_compare_melted,
    palette='viridis'   # ✅ Your color palette
)

plt.title('Comparison of Transformer Model Performance')
plt.ylabel('Score')
plt.xlabel('Model')
plt.ylim(0, 1)
plt.xticks(rotation=45)
plt.legend(title='Metric')
plt.tight_layout()
plt.show()